App\Entity\Notification:
    type: entity
    table: notification
    uniqueConstraints:
        fk_branch_office_idx:
            columns:
                - branch_office_fk
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        output:
            type: integer
            nullable: true
            options:
                unsigned: false
        reception:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        branchOfficeFk:
            targetEntity: BranchOffice
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                branch_office_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
