App\Entity\Profile:
    type: entity
    table: profile
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        level:
            type: string
            nullable: true
            length: 55
            options:
                fixed: false
    lifecycleCallbacks: {  }
