App\Entity\Travel:
    type: entity
    table: travel
    indexes:
        fk_vehicle_idx:
            columns:
                - vehicle_fk
        fk_driver_idx:
            columns:
                - driver_fk
        fk_notification_idx:
            columns:
                - notification_fk
        fk_transport_idx:
            columns:
                - transport_fk
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        startDate:
            type: datetime
            nullable: true
            column: start_date
        endDate:
            type: datetime
            nullable: true
            column: end_date
    manyToOne:
        driverFk:
            targetEntity: Driver
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                driver_fk:
                    referencedColumnName: id
            orphanRemoval: false
        notificationFk:
            targetEntity: Notification
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                notification_fk:
                    referencedColumnName: id
            orphanRemoval: false
        transportFk:
            targetEntity: Transport
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                transport_fk:
                    referencedColumnName: id
            orphanRemoval: false
        vehicleFk:
            targetEntity: Vehicle
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                vehicle_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
