App\Entity\Vehicle:
    type: entity
    table: vehicle
    indexes:
        fk_origin_idx:
            columns:
                - origin_fk
        fk_branch_office_idx:
            columns:
                - branch_office_fk
        fk_state_idx:
            columns:
                - state_fk
        vehicle_type_fk_idx:
            columns:
                - vehicle_type_fk
        fk_automotive_idx:
            columns:
                - automotive_fk
        fk_priority_idx:
            columns:
                - priority_fk
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idChassis:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: id_chassis
        mark:
            type: string
            nullable: true
            length: 55
            options:
                fixed: false
        color:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        requestDate:
            type: datetime
            nullable: true
            column: request_date
    manyToOne:
        stateFk:
            targetEntity: State
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                state_fk:
                    referencedColumnName: id
            orphanRemoval: false
        automotiveFk:
            targetEntity: Automotive
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                automotive_fk:
                    referencedColumnName: id
            orphanRemoval: false
        branchOfficeFk:
            targetEntity: BranchOffice
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                branch_office_fk:
                    referencedColumnName: id
            orphanRemoval: false
        originFk:
            targetEntity: Origin
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                origin_fk:
                    referencedColumnName: id
            orphanRemoval: false
        priorityFk:
            targetEntity: Priority
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                priority_fk:
                    referencedColumnName: id
            orphanRemoval: false
        vehicleTypeFk:
            targetEntity: VehicleType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                vehicle_type_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
